version: "3.9"
services:
  ap:
    build:
      context: .docker/ap
      args:
        USER: ${USER}
        UID: 1000
        GROUP: ${USER}
        GID: 1000
    command: tail -f
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

volumes:
  bundle:
